declare module 'vue-swatches'
declare module '@/views/WardrobeOverviewPage.vue'
declare module '@/views/AddClothingPage.vue'
declare module '@/views/WashingPage.vue'
declare module '@/views/RegisterPage.vue'
declare module '@/views/LoginPage.vue';
declare module '@/views/RegisterPage';
declare module '@/views/TabsPage.vue';
declare module '@/components/ModalDialogAddClothingItem.vue';
declare module '@/components/ImageInput';