INSERT INTO
    `material` (`ID`, `material`)
VALUES
    ('1', 'Cotton'),
    ('2', 'Polyester'),
    ('3', 'Viscose'),
    ('4', 'Merino wool'),
    ('5', 'Wool');

INSERT INTO
    `status` (`ID`, `status`)
VALUES
    ('1', 'clean'),
    ('2', 'okay'),
    ('3', 'dirty');

INSERT INTO
    `washing_mode` (`ID`, `washing_mode`)
VALUES
    ('1', '40 degrees, colors'),
    ('2', '30 degrees, fine wash, dark');

INSERT INTO
    `weather` (`ID`, `weather`)
VALUES
    ('1', 'sunny'),
    ('2', 'cloudy'),
    ('3', 'rain'),
    ('4', 'snow');

INSERT INTO
    `brand` (`ID`, `name`)
VALUES
    (1, 'Asos'),
    (2, 'H&M');

INSERT INTO
    `occasion` (`ID`, `occasion`)
VALUES
    ('1', 'Work'),
    ('2', 'Home'),
    ('3', 'Party');

INSERT INTO
    `color` (`id`, `hex_code`, `name`)
VALUES
    (0, '#b5251b', 'red'),
    (1, '#FF8838', 'orange'),
    (2, '#E7E31E', 'yellow'),
    (3, '#90EE90', 'light green'),
    (4, '#1f911d', 'green'),
    (5, '#00693E', 'dark green'),
    (6, '#10C09A', 'turquoise'),
    (7, '#067467', 'teal'),
    (8, '#89CFF0', 'light blue'),
    (9, '#2074bd', 'blue'),
    (10, '#000080', 'navy'),
    (11, '#771cb0', 'violet'),
    (12, '#ffffff', 'white'),
    (13, '#000000', 'black'),
    (14, '#515151', 'grey'),
    (15, '#59260B', 'brown'),
    (16, '#FF6FCA', 'rose'),
    (17, '#DBD7D2', 'beige'),
    (18, '#BEBFC5', 'light grey'),
    (19, '#800020', 'burgundy'),
    (20, '#8D0A59', 'magenta'),
    (21, '#C18363', 'light brown');

INSERT INTO
    `brand` (`name`)
VALUES
    ('Armedangels'),
    ('Bershka'),
    ('Cecil'),
    ('Comma'),
    ('Calvin Klein'),
    ('Converse'),
    ('DeFacto'),
    ('Desigual'),
    ('Diesel'),
    ('Esprit'),
    ('Edited'),
    ('Ellesse'),
    ('Fransa'),
    ('Fjällräven'),
    ('GAP'),
    ('Hummel'),
    ('Hunkemöller'),
    ('Hollister'),
    ('Hessnatur'),
    ('Icebreaker'),
    ('Kaffe'),
    ('KUNERT'),
    ('Lascana'),
    ("levi's"),
    ("Marc O'Polo"),
    ('Mango'),
    ('Noisy May'),
    ('Nike'),
    ('Nasty Gal'),
    ('Naketano'),
    ('Only'),
    ('Orsay'),
    ('Object'),
    ('Pieces'),
    ('Puma'),
    ('Pull&Bear'),
    ('Pepe Jeans'),
    ('Rieker'),
    ('Reebok'),
    ('S.Oliver'),
    ('Street One'),
    ('Skechers'),
    ('Schiesser'),
    ('Selected Femme'),
    ('Tamaris'),
    ('Tom Tailor'),
    ('Tommy Hilfiger'),
    ('Topshop'),
    ('The North Face'),
    ('United Colors of Benetton'),
    ('VERO MODA'),
    ('Vila'),
    ('Vans'),
    ('Weekday'),
    ('Zero');

INSERT INTO
    `material` (`material`)
VALUES
    ('Linen'),
    ('Polyester'),
    ('Leather'),
    ('Lace'),
    ('Crepe'),
    ('Twill'),
    ('Nylon'),
    ('Silk'),
    ('Satin'),
    ('Cashmere'),
    ('Rayon'),
    ('Denim'),
    ('Velvet'),
    ('Cotton'),
    ('Wool'),
    ('Chiffon'),
    ('Hemp'),
    ('Jersey'),
    ('Merino wool'),
    ('Modal'),
    ('Muslin'),
    ('Organza'),
    ('Elastane'),
    ('Tweed'),
    ('Viscose'),
    ('Felt'),
    ('Microfiber'),
    ('Bamboo'),
    ('Polyamide'),
    ('Mohair'),
    ('Alpaca wool'),
    ('Angora'),
    ('Egyptian cotton'),
    ('Flannel'),
    ('Suede'),
    ('Lyocell');

INSERT INTO
    `parent_category` (`name`)
VALUES
    ('top'),
    ('t-shirt'),
    ('dress'),
    ('jumper'),
    ('coat'),
    ('jeans'),
    ('jacket'),
    ('trousers'),
    ('skirt'),
    ('blouse'),
    ('shirt'),
    ('shoes'),
    ('other');

INSERT INTO
    `category` (`ID_partent_category`, `type`)
VALUES
    (0, 'off-shoulder top'),
    (0, 'bralette top'),
    (0, 'crop top'),
    (0, 'bustier top'),
    (0, 'camisole'),
    (0, 'empire line top'),
    (0, 'halter top'),
    (0, 'henley neck top'),
    (0, 'one shoulder top'),
    (0, 'poncho'),
    (0, 'spaghetti strap top'),
    (0, 'tank top'),
    (0, 'workout top'),
    (1, 'polo t-shirt'),
    (1, 'half sleeves'),
    (1, 'v-neck'),
    (1, 'henley t-shirt'),
    (1, 'hooded t-shirt'),
    (1, 'u-neck'),
    (1, 'long-sleeves'),
    (1, 'graphic t-shirt'),
    (1, 'sleeveless t-shirt'),
    (1, 'pocket t-shirt'),
    (2, 'knit dress'),
    (2, 'evening dress'),
    (2, 'cocktail dress'),
    (2, 'mini dress'),
    (2, 'shirt dress'),
    (2, 'midi dress'),
    (2, 'summer dress'),
    (2, 'maxi dress'),
    (2, 'sheath dress'),
    (2, 'denim dress'),
    (2, 'lace dress'),
    (2, 'beach dress'),
    (2, 'dungaree dress'),
    (3, 'pullover'),
    (3, 'poncho'),
    (3, 'kimono'),
    (3, 'hoodie'),
    (3, 'full zip'),
    (4, 'winter coat'),
    (4, 'wool coat'),
    (4, 'between-seasons coat'),
    (4, 'short coat'),
    (4, 'trenchcoat'),
    (4, 'rain coat'),
    (4, 'duffle coat'),
    (4, 'down coat'),
    (4, 'box coat'),
    (4, 'cape coat'),
    (4, 'parka coat'),
    (4, 'wrap coat'),
    (5, 'skinny fit'),
    (5, 'straight leg'),
    (5, 'regular fit'),
    (5, 'wide leg'),
    (5, 'mom jeans'),
    (5, 'boyfriend jeans'),
    (5, 'jeggings'),
    (5, 'shorts'),
    (5, 'slim fit'),
    (5, 'dungarees'),
    (5, 'loose fit'),
    (5, 'relaxed fit'),
    (5, 'boot cut'),
    (5, 'baggy fit'),
    (6, 'winter jacket'),
    (6, 'gilet'),
    (6, 'quilted jacket'),
    (6, 'puffer jacket'),
    (6, 'parka'),
    (6, 'leather jacket'),
    (6, 'bomber jacket'),
    (6, 'down jacket'),
    (6, 'denim jacket'),
    (6, 'rain jacket'),
    (6, 'outdoor jacket'),
    (6, 'anorak'),
    (6, 'baseball jacket'),
    (6, 'blazer'),
    (6, 'bolero'),
    (6, 'cardigan'),
    (6, 'cropped jacket'),
    (6, 'kimono'),
    (6, 'motorcycle jacket'),
    (6, 'shirt jacket'),
    (6, 'shrug jacket'),
    (6, 'windbreaker'),
    (7, 'fabric trousers'),
    (7, 'leggings'),
    (7, 'leather trousers'),
    (7, 'tracksuit pants'),
    (7, 'shorts'),
    (7, 'corduroy trousers'),
    (7, 'wide leg trousers'),
    (7, 'cargo pants'),
    (7, 'pleated trousers'),
    (7, 'chino pants'),
    (7, 'culottes'),
    (7, 'harem trousers'),
    (7, 'sweatpants'),
    (7, 'yoga pants'),
    (8, 'a-line skirt'),
    (8, 'pencil skirt'),
    (8, 'gathered skirt'),
    (8, 'mini skirt'),
    (8, 'flared skirt'),
    (8, 'draped skirt'),
    (8, 'layered skirt'),
    (8, 'circle skirt'),
    (8, 'mermaid skirt'),
    (8, 'wrap skirt'),
    (8, 'pleated skirt'),
    (8, 'midi skirt'),
    (8, 'maxi skirt'),
    (8, 'denim skirt'),
    (8, 'leather skirt'),
    (9, 'shirt'),
    (9, 'long blouse'),
    (9, 'short blouse'),
    (9, 'lace blouse'),
    (9, 'denim shirt'),
    (9, 'long-sleeved blouse'),
    (9, 'short-sleeved blouse'),
    (9, 'sleeveless blouse'),
    (9, 'tunic'),
    (10, 'oxford button-down shirt'),
    (10, 'dress shirt'),
    (10, 'short-sleeved shirt'),
    (10, 'cuban collar shirt'),
    (10, 'flanell shirt'),
    (10, 'overshirt'),
    (10, 'linen shirt'),
    (10, 'work shirt'),
    (10, 'denim shirt'),
    (10, 'chambray shirt'),
    (11, 'jewelry'),
    (11, 'bag'),
    (11, 'purse'),
    (11, 'hat'),
    (11, 'cap'),
    (11, 'beanie'),
    (11, 'scarf'),
    (11, 'shawl'),
    (11, 'belt'),
    (11, 'gloves'),
    (11, 'mittens'),
    (11, 'hairband'),
    (11, 'headband'),
    (11, 'tie'),
    (11, 'bow tie'),
    (11, 'socks'),
    (11, 'tights'),
    (12, 'sneakers'),
    (12, 'loafers'),
    (12, 'espadrilles'),
    (12, 'ballet flats'),
    (12, 'moccasins'),
    (12, 'slip-ons'),
    (12, 'mary janes'),
    (12, 'slippers'),
    (12, 'sandals'),
    (12, 'flip-flops'),
    (12, 'ankle boots'),
    (12, 'chelsea boots'),
    (12, 'combat boots'),
    (12, 'knee-high boots'),
    (12, 'hiking boots'),
    (12, 'oxfords'),
    (12, 'borgues'),
    (12, 'derbies'),
    (12, 'monk straps'),
    (12, 'running shoes'),
    (12, 'tennis shoes'),
    (12, 'stilettos'),
    (12, 'wedges'),
    (12, 'high heels'),
    (12, 'block heels'),
    (12, 'kitten heels'),
    (12, 'platform shoes'),
    (13, 'swimsuit'),
    (13, 'bikini'),
    (13, 'pajama'),
    (13, 'loungewear'),
    (13, 'workout clothing'),
    (13, 'lingerie'),
    (13, 'nightgown'),
    (13, 'robe'),
    (13, 'bra'),
    (13, 'pocket square'),
    (13, 'dancewear'),
    (13, 'apron'),
    (13, 'costume'),
    (13, 'workwear'),
    (13, 'dance shoes'),
    (13, 'underwear'),
    (13, 'other'),